### PR TITLE
Java build fixed

### PR DESCRIPTION
**Pull request by chathurawidanage**

### CODE REVIEW

**Comment by supunkamburugamuve** [comment]
@chathurawidanage are we shipping the so with the jar?

**Comment by chathurawidanage** [comment]
> @chathurawidanage are we shipping the so with the jar?

Yes.. libcylon.so and libcylonjni.so are included in the jar...

**Comment by supunkamburugamuve** [comment]
Great. What do you think about linking arrow and glog statically to libcylon and include in the jar?

**Comment by supunkamburugamuve** [comment]
glog is already linked statically. For the java case, we can build cylon with static arrow libraries. or we can put the arrow library inside the jar as well.

**Comment by chathurawidanage** [comment]
A few months back, when I tried to load arrow.so to JVM, it failed. I'll try again to see if it works..

**Comment by supunkamburugamuve** [comment]
In that case, shall we link it statically to cylon for Java?

**Comment by chathurawidanage** [comment]
I tried this approach. But seems we might have to include few other libs including openmpi libs if the jar needs to be standalone.

**Comment by supunkamburugamuve** [comment]
Got you. I think may. be a better approach for us is to decouple distributed from local and provide those as two separate libraries. That will make it easier to ship the local version.

**Review by supunkamburugamuve — APPROVED** [review]

**Pull request merged**
