### PR TITLE
adding finalize check and removing destructor finalize call.

### PR DESCRIPTION
**Pull request by vibhatha**

### CODE REVIEW

**Comment by chathurawidanage** [comment]
This might break the examples. Shall we explicitly add the finalize call to the examples?

**Comment by vibhatha** [comment]
> This might break the examples. Shall we explicitly add the finalize call to the examples?

added.

**Review by nirandaperera — APPROVED** [review]

**Comment by nirandaperera** [comment]
On a separate note, shall we add closeable interface to the env?

**Comment by vibhatha** [comment]
> On a separate note, shall we add closeable interface to the env?

Yes, I think it will be interesting to add that kind of functionality. Let's review this one separately.

**Pull request merged**
